# Generated by Django 4.2.5 on 2024-06-19 07:54

import audit_system.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', audit_system.models.CustomUserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
