# Generated by Django 4.2.5 on 2024-06-21 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audit_system', '0002_alter_user_managers_rename_name_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('manager', 'manager'), ('supervisor', 'supervisor'), ('auditor', 'auditor'), ('assistant', 'assistant')], max_length=20),
        ),
        migrations.CreateModel(
            name='FileLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_description', models.TextField()),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('file_logged', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='audit_system.file')),
                ('user_logged', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
