# Generated by Django 4.2.5 on 2024-06-21 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit_system', '0003_alter_user_role_filelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filelog',
            name='update_at',
        ),
    ]
